version: '3.8'
services:
  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metacatalog
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://127.0.0.1:8000/api/
    ports:
      - 8000:8000
    environment:
      METACATALOG_URI: postgresql://postgres:postgres@db:5432/metacatalog
      HOST: 0.0.0.0
      PORT: 8000


