version: '3.8'
services:
  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metacatalog
    expose:
      - 5433
    ports:
      - 5433:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data


